### PR TITLE
Minorfixes

### PR DESCRIPTION
**Pull request by barrybingo**
Two little things to fix compiler errors.
Compilation succeeds on VS2017 and gcc 8.3

### CODE REVIEW

**Comment by barrybingo** [comment]
index is deprecated so has been replaced.  Could also replace function with 
    #define index(a,b) strchr((a),(b))

**Comment by mtrojnar** [comment]
Initializing the pointer with NULL not only does not address the root cause (using a variable that was not assigned a meaningful value), but also makes the root cause even harder to find.

**Comment by mtrojnar** [comment]
I agree with replacing index() with strchr().

**Comment by barrybingo** [comment]
Ok I fixed the sig uninitialized error in VS by treating it as warning; so can ignore that patch.

**Pull request merged**
