### PR TITLE
Delete the output file in case of error

### LINKED ISSUE #313: 0Kb file if input file is the same as output file
It seems that osslsigncode doesn't support setting your input file as the same as the output file (to overwrite the input file). 

However, this seems to be handled ungracefully, it results in the error:

`Unrecognized file type - file is too short: <input file.exe>` and leaves the input/output file as a 0kb file. 

Support for overwriting the input file is a pretty handy feature since signing an executable is generally one step amongst many others as part of a build pipeline, but at the least if support is not intended I feel there should be a dedicated error message, as this may confuse some.

### PR DESCRIPTION
**Pull request by olszomal**
Fix #313

### CODE REVIEW

**Comment by mtrojnar** [comment]
Won't it delete the input file if the input file and the output file are the same?

**Comment by olszomal** [comment]
If the input file and the output file are the same, the program will fail to create the output file and will exit without deleting the file.

**Comment by mtrojnar** [comment]
> If the input file and the output file are the same, the program will fail to create the output file and will exit without deleting the file.

Are you saying that it was not possible to replicate the bug described in #313?  Could this issue be specific to a particular host operating system?

**Comment by olszomal** [comment]
The error:
```
Unrecognized file type - file is too short: <input file.exe>
```
says that the `<input file.exe>` input file may have previously been saved as a 0kb file.

I fixed the issue of  leaving the output file as a 0kb file in case of error.

@Niaxor Could you take a look?

**Comment by mtrojnar** [comment]
On Windows, `test.exe`, `TEST.EXE` and `.\test.exe` are all the same file.  I'd prefer osslsigncode to never overwrite an existing file.

**Pull request merged**
